name: Android CI

on:
  push:
    branches: [ "android-pipeline" ]
  pull_request:
    branches: [ "android-pipeline" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: ./android-project
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./android-project
      run: ./gradlew assembleRelease
    - name: debug
      uses: actions/upload-artifact@v4
      with:
        name: files
        path: ./
        overwrite: true
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: resl.apk
        path: ./android-project/app/build/outputs/apk/release/app-release-unsigned.apk
        overwrite: true
        if-no-files-found: error
