name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: ./android-project
      run: chmod +x gradlew
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.KEYSTORE }}
      run: |
        KEYSTORE_FILE_PATH=./android-project/app/keystore
        mkdir "${KEYSTORE_FILE_PATH}"
        echo $ENCODED_STRING | base64 -di > "${KEYSTORE_FILE_PATH}"/resl_keystore.jks
    - name: Build with Gradle
      working-directory: ./android-project
      run: |
        ./gradlew assembleRelease
        ./gradlew bundleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        VERSION_CODE: ${{ github.run_number }}
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: resl-${{ github.run_number }}.apk
        path: ./android-project/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
    - name: Upload AAB bundle
      uses: actions/upload-artifact@v4
      with:
        name: resl-${{ github.run_number }}.aab
        path: ./android-project/app/build/outputs/bundle/release/app-release.aab
        if-no-files-found: error
