name: WebAssembly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mymindstorm/setup-emsdk@v14

    - name: check emscripten version
      run: emcc -v

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        emcmake cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_NUMBER=${{ github.run_number }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Upload WASM artifacts
      if: "${{ matrix.os == 'windows-latest' }}"
      uses: actions/upload-artifact@v4
      with:
        name: resl-wasm-release-${{ github.run_number }}
        path: ${{ steps.strings.outputs.build-output-dir }}/${{ matrix.build_type }}/
        if-no-files-found: error

    - name: Upload artifacts
      if: "${{ matrix.os != 'windows-latest' }}"
      uses: actions/upload-artifact@v4
      with:
        name: resl-wasm-release-${{ github.run_number }}
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/resl.js
          ${{ steps.strings.outputs.build-output-dir }}/resl.wasm
        if-no-files-found: error
